### ISSUE TITLE
OPEN and CLOSED are backwards

### ISSUE THREAD

**Issue by SteveRMann** [drmibell/node-red-contrib-simple-gate#1]
Since nodes in Node-Red are connected by virtual 'wires', not 'pipes', then the terminology should be electrical, not plumbing.

OPEN should mean that the switch is open and current doesn't flow.
CLOSED should mean that the switch is closed and current flow is allowed.

**Comment by drmibell** [comment]
Good point. Unfortunately, in this case precision in language may prevent clarity in communication. This function has been referred to as a "gate" for least two years, including by one of the NR developers ( [https://flows.nodered.org/flow/a985944e789d90e0cd2008d85b7aaa65](url)   `Simple gate to switch on and off a flow`)  One of the core nodes is already called `switch` (single-pole, multi-throw) in spite of the fact that it does not retain its state. Clearly, the terminology is a bit of a mixed metaphor, but I think we are stuck with it. Everything here is open source, so you are free to clone the node and change the labels and documentation to suit your needs.
