### ISSUE TITLE
small issue with the documentation: "Control Topic"

### ISSUE THREAD

**Issue by Urs-Eppenberger** [drmibell/node-red-contrib-simple-gate#10]
In the Information panel to the node I read the following:
Messages with the topic Control Topic are control messages, which set the state of the gate. 

The two words Control Topic are in red. I thought that I need to set
  msg.topic = "Control Topic";
but it seems that
  msg.topic = "Control";
is the correct setting. In my personal view the text is slightly misleading.
Without the red word 'Topic' I probably would have made it in the first try (and probably would made other errors).

Maybe you look at it and decide yourself.
Kind regards,
Urs.

**Comment by drmibell** [comment]
If you look at the node's edit dialog, you will see that `Control Topic` is the name of the parameter (string) that the user can define to be the topic for control messages. The default value for that parameter is "control", but you can set it as you like. I think you will find that this sort of usage to distinguish between the name of a parameter and its value is fairly standard in Node-RED and does not generally lead to confusion.
