### ISSUE TITLE
Request: release info

### ISSUE THREAD

**Issue by DarkPark** [drmibell/node-red-contrib-simple-gate#13]
Please provide release info available on page https://github.com/drmibell/node-red-contrib-simple-gate/releases

It's very convenient to see changlelog and it's possible to subscribe on these releases to be in the loop.

**Comment by colinl** [comment]
Hi Michael. I do this with my nodes. It is very easy and I think worthwhile.  These are my notes on how to do it.  I always make notes about things that I don't do every day.

Releasing a new version release on github:
Having committed and pushed to github (not tagged), click on Code, then Create a new release (under Releases in the right hand panel) then Draft a new Release
Fill in a tag name (eg v1.0.1) title (eg Version 1.0.1) and description and Publish
Pull local repo to pickup tag

Then you end up with something like this https://github.com/colinl/node-red-contrib-pid/releases
