### ISSUE TITLE
closed gate not blocking all payloads

### ISSUE THREAD

**Issue by thomasvjohansen** [drmibell/node-red-contrib-simple-gate#14]
Hi

Great gate function, though it seems its not blocking all payloads. I have an Ikea motion sensor using a zigbee2mqtt-devices node, which unfortunately can pass through you closed gate node.

I cant give you its exact payload output, for some strange reason I cant get the debug node to pickup anything from it.

**Comment by colinl** [comment]
If the debug node is not showing anything at all then the gate node is not sending anything, which suggests that perhaps you have misinterpreted what you are seeing.

**Comment by thomasvjohansen** [comment]
it is sending something because it can turn on my light in my flow. so strange.

**Comment by thomasvjohansen** [comment]
![billede](https://user-images.githubusercontent.com/15713353/147120114-7c1aea1e-fd1f-4c85-b1cf-7cb57728a642.png)

Here you can see it can turn on my lights even though the gate i closed

**Comment by colinl** [comment]
If you think that you have found a bug in both the gate node and the debug node then add a function node after the gate node with 
```
node.warn("Out of gate")
return msg
```
and add one before the gate node with
```
node.warn("Into gate")
return msg
```
Then try again.  If that also shows that a message is going in but does not show the message coming out, but your light still goes on then I think something else is switching the light.

**Comment by colinl** [comment]
Looking at the flow you posted I see there are numerous other paths that could switch the light.  Perhaps it is happening via one of those routes.  Try disconnecting the wire out of the gate and see if it still happens.

**Comment by thomasvjohansen** [comment]
![billede](https://user-images.githubusercontent.com/15713353/147121429-f9e3e61a-7ca5-43fa-a4c7-2ae640f9006c.png)
it still sets the spots to full lm 254, even though gate is closed.

**Comment by thomasvjohansen** [comment]
![billede](https://user-images.githubusercontent.com/15713353/147121829-94cd229b-c910-4633-ba1f-6e051c204665.png)

there is something completely wrong, its my flow somewhere. even if its not connected it turns on... Sorry for bothering you.

**Comment by thomasvjohansen** [comment]
![billede](https://user-images.githubusercontent.com/15713353/147124190-340a7186-335c-4313-8406-4a60132d6915.png)
Here is my working flow -working great with 3 gate nodes. 
One gate node is controlled by bigtimer so motionsensor cant turn on light when bigtimer dont allow it. And motion sensor uses two gates to block bigtimers control when sensor is detecting motion. 

Thx for your gate node.
