### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by Just-another-pleb** [drmibell/node-red-contrib-simple-gate#15]
I am hoping this is the right node.   I am going on the icon used more than anything.  (See below)
That you can select between `TEXT` and `NUMBER` values.

I have written a basic bit of code upstream from this node.
It is a toggle and so uses `0` and `1` values.

To keep things simple the `0` and `1` are sent out as the messages.

But I can't use them to control your node.

To get it working I need a lot more code to convert from number to text.  :(

(Oh, P.S.)
The name used isn't helping.
In NR it is called `GATE` yet here it is `SIMPLE-GATE`.   So which is it?

**Comment by colinl** [comment]
If you have installed node-red-contrib-simple-gate then the `gate` node is this.  If you have installed something else that provides a `gate` node then it will be that one you are seeing.  You can tell what you have installed, if you can't remember, by looking in Manage Palette.

To convert your numbers to strings you can use a Function node containing
```
msg.payload = msg.payload.toFixed(0)
return msg
```

**Comment by Just-another-pleb** [comment]
Ok.

But in the *editor* it is called... `gate`.   Going to the palette manager `gate` doesn't exist.

This is what isn't helping me with identifying things.

*Who is who*?

![Screenshot from 2022-01-22 08-52-40](https://user-images.githubusercontent.com/39888280/150605430-8e172aac-3b8b-43c6-9468-8c372cc07fbd.png)

![Screenshot from 2022-01-22 08-52-51](https://user-images.githubusercontent.com/39888280/150605458-b59b50d6-7ff4-4cf3-99d7-948a3b532893.png)

![Screenshot from 2022-01-22 08-52-56](https://user-images.githubusercontent.com/39888280/150605483-797c76f5-ceb7-4180-80a8-b671c7c85b11.png)

I once got really messed up because there is another gate (queue actually) and it had me going in circles for a long time.

I like your queue/gates in some ways, but the other one once snuck into the system and (as I said) had me going in circles because of names.

Yes, I could just add that function node to do that trick - which is what I did.
I think I did something close to that.

I am only suggesting you put that option in your node to allow either letters or numbers.
So really those should also be allowed also.

Oh, I think the other queue/gate node was used early on as I was using the `true` / `false` signals - as they seem prevalent for that scenario - and yours didn't.

I get it that it makes the code for the node bigger and if not many people use it....
There is a trade off.

Thanks.

**Comment by colinl** [comment]
For the record, I am not the author.

Nodes cannot sneak in, you have to install them, unless they are supplied as part of the node-red core.

Try clicking on the button below the node name.
![image](https://user-images.githubusercontent.com/38307/150606880-0c0e8538-7b4b-476d-ab9b-eb3b27ce6e60.png)

@drmibell  might well consider whether typed inputs would be useful, though as far as I can remember this is the first time this has been requested.

**Comment by Just-another-pleb** [comment]
I said "snuck in" only because it was a left over from early days when I was using `TRUE` / `FALSE` messages to indicate things and so to trigger the `gate` node.  That was nice.

Things moved on and this *series* of nodes seemed better and so I migrated to them - and missed a couple of old ones that caused me grief.

I am requesting it because - as I said - I was doing some toggling code and `0` and `1` were the output.
It seemed nice to just pass them on.
But as the node doesn't like/accept numbers, it is a problem.

The `function` node resolved this problem but I think it would be nicer if that was all hidden in the node's code.

**Comment by drmibell** [comment]
From the README:
`if a control message is received with a payload that is a number or boolean, the payload is converted to a string and then tested against the command definitions.`
A number or boolean payload should be able to control the gate. If this is not working, please post a flow that shows the failure.

Your confusion about naming comes partly from the distinction between the npm package name (node-red-contrib-simple-gate) and the node name (gate).

**Comment by Just-another-pleb** [comment]
Um, sorry.

You do seem to be right.

The *gremlins* ran away as soon as you replied.
Things do seem to be working now and I am not sure why they weren't before.

Again:  Sorry.

**Comment by Just-another-pleb** [comment]
Sorry....

It worked, I posted / closed it and then it stopped working again.

```
[{"id":"402169a8.8a791","type":"subflow","name":"B Toggle 2","info":"##\nAny message in.   `UP` is reserved to make the output state to `OFF`\n\nOutputs:\n1 - `0` for OFF and `1` for ON\n2 - to be sent back to button with `msg.colour` to set buttons colour\n","category":"","in":[{"x":140,"y":120,"wires":[{"id":"248202b.2d1507e"}]}],"out":[{"x":640,"y":120,"wires":[{"id":"248202b.2d1507e","port":0}]},{"x":640,"y":170,"wires":[{"id":"248202b.2d1507e","port":1}]},{"x":640,"y":220,"wires":[{"id":"f3bc4046.86bd68","port":0},{"id":"b1252f0.51480d","port":0}]}],"env":[],"color":"#D8BFD8","icon":"node-red-dashboard/ui_switch.png"},{"id":"248202b.2d1507e","type":"function","z":"402169a8.8a791","name":"toggle","func":"var topic = env.get(\"topic\");\nvar x = context.get(\"counter\") || 0;\nvar y;\nif (msg.payload == \"Up\")\n{\n    context.set(\"counter\",0);\n    msg.payload = 0;\n    return msg;\n}\n\nmsg1 = {};\n\nif (x === 0)\n{\n    msg.payload = 1;\n} else\nif (x === 1)\n{\n    msg.payload = 0;\n}\n\nx = (x + 1) % 2;\ny = (x + 1) % 2;\n\nmsg1.payload = y;\nmsg1.topic = topic;\n\nmsg.topic = topic;\n\ncontext.set(\"counter\",x);\n\nreturn [msg,msg1];","outputs":2,"noerr":0,"initialize":"","finalize":"","libs":[],"x":240,"y":120,"wires":[["1f2c3cd.bc88643"],[]],"info":"##  Outputs `1` or `0` for ON/OFF and `msg.colour` to send to button."},{"id":"1f2c3cd.bc88643","type":"switch","z":"402169a8.8a791","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"0","vt":"num"},{"t":"eq","v":"1","vt":"num"}],"checkall":"true","repair":false,"outputs":2,"x":380,"y":220,"wires":[["f3bc4046.86bd68"],["b1252f0.51480d"]]},{"id":"f3bc4046.86bd68","type":"change","z":"402169a8.8a791","name":"Red","rules":[{"t":"set","p":"colour","pt":"msg","to":"red","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":500,"y":190,"wires":[[]]},{"id":"b1252f0.51480d","type":"change","z":"402169a8.8a791","name":"Lime","rules":[{"t":"set","p":"colour","pt":"msg","to":"lime","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":500,"y":250,"wires":[[]]},{"id":"e193ef9be7821f24","type":"inject","z":"a1911aa3.c45be8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"X","payloadType":"str","x":2480,"y":1180,"wires":[["913bd965c91566f1"]]},{"id":"913bd965c91566f1","type":"subflow:402169a8.8a791","z":"a1911aa3.c45be8","name":"","env":[{"name":"topic","value":"control","type":"str"}],"x":2690,"y":1300,"wires":[["ab99d6fdd2cda4d9","a8f84aefc8052bb6"],[],["93bbd0a8f9f47f7c"]]},{"id":"a8f84aefc8052bb6","type":"gate","z":"a1911aa3.c45be8","name":"A","controlTopic":"control","defaultState":"closed","openCmd":"0","closeCmd":"1","toggleCmd":"toggle","defaultCmd":"default","persist":false,"x":2670,"y":1360,"wires":[["76bb56e79d4fc3ce"]]}]
```

It will be something stupid I am doing, but I can't see it.
