### ISSUE TITLE
Bug: status message does not work

### ISSUE THREAD

**Issue by Sp0rTB4cK** [drmibell/node-red-contrib-simple-gate#17]
I was wondering today when using the gate node that I don't get a message when requesting the current status.

Apparently the problem is that the switch case for the status is missing the necessary code. 

See:
https://github.com/drmibell/node-red-contrib-simple-gate/blob/b547e21a9e3b0683fba1c3f79f5790a391989baf/gate.js#L82

The case is empty. Is that on purpose?

**Comment by Sp0rTB4cK** [comment]
Oh, sorry. I missed that I have to use a status node to read out the status.

**Comment by davidsavoie1** [comment]
Hello! I'd like to revive this issue, since the documentation states:

> Messages with the topic Control Topic are control messages, which set the state of the gate. Control messages can have values representing open, close, toggle, default, and status.

It seems a control message with a `status` payload should return something, no?

Thank you in advance.

**Comment by drmibell** [comment]
The documentation states:
 
> The `status` command (added in version 0.4.0) causes the node status to be refreshed, so that it can be caught by a `status` node.

This is shown in the Basic Operation example.

None of the control messages produces an output from the node.

**Comment by davidsavoie1** [comment]
Oh! I'm sorry, I didn't understand it that way at all. I had read the node's UI documentation only; the behavior is well documented in the README of the library. My bad!

Thanks again, this is a very useful node!

**Comment by drmibell** [comment]
No problem. Most documentation is write-only most of the time. I'm glad you find the node useful.
