### ISSUE TITLE
Node name

### ISSUE THREAD

**Issue by Paul-Reed** [drmibell/node-red-contrib-simple-gate#4]
In the dashboard 'Info panel', the node is only referred to as 'gate', so unless users can remember which node was installed/used, it could potentially be node-red-contrib-message-gate, queue-gate, simple-gate, etc.
Also if sharing a flow, and the new user doesn't have your node already installed, node-RED will halt awaiting the node 'gate' to be registered, but which one?

![gate](https://user-images.githubusercontent.com/973580/49702584-a3499a00-fbf1-11e8-9520-96c6a3f5dce1.PNG)

If [this line was changed](https://github.com/drmibell/node-red-contrib-simple-gate/blob/master/gate.js#L83) to more accurately reflect the node's name (simple-gate), it would make it much easier to identify.

This is a very minor issue, which you may wish to consider when you next update the node.

**Comment by drmibell** [comment]
Good idea. The node was built for my own use and published just as the "competition" (confusion) was beginning to appear. I'll plan a fix for the next update, but are you sure that [this](https://github.com/drmibell/node-red-contrib-simple-gate/blob/master/gate.js#L83) is the only change needed? I may need changes in the .html file also.

**Comment by Paul-Reed** [comment]
> are you sure that this is the only change needed? 
No, sorry I can't be sure.
It was probably presumptuous of me to quote that link alone.

**Comment by drmibell** [comment]
No worries. You pointed me in the right direction, and I'll follow up.

**Comment by drmibell** [comment]
You have described two distinct issues. First,
> In the dashboard 'Info panel', the node is only referred to as 'gate', so unless users can remember which node was installed/used, it could potentially be node-red-contrib-message-gate, queue-gate, simple-gate, etc.

This doesn't justify a name change. The Manage Palette panel lists all the contributed packages installed, and for each one there is a toggle labeled "> n node(s)" that shows the names of each node in the package. Some effort is required, but the information is available.

> Also if sharing a flow, and the new user doesn't have your node already installed, node-RED will halt awaiting the node 'gate' to be registered, but which one?

This is more difficult, and the question has come up in the forum several times recently. Obviously, if the author of a contributed node can come up with unique node names, clearly tied to the name of his package, that's great. (Keep in mind that many packages contain more than one node, and nothing prevents another contributor from later giving different nodes the same names.) The only sure-fire solution is for the person publishing or sharing a flow to identify the required package.

In the case of `node-red-contrib-simple-gate` I would want to do my part if I could start from scratch, but changing the name at this point could make things worse. There would effectively be two different nodes out there, `gate` and `simple-gate`. A user with one of them installed would still have difficulty importing a flow containing the other one. Worse yet, if he deleted `gate` and installed `simple-gate`, his own flows (both in the editor and in the library) would have to be edited to use the new one. I have tried and failed to find a work-around for this, and without one I am reluctant to make a change.

**Comment by Paul-Reed** [comment]
No worries, thanks for looking.
