### ISSUE TITLE
Feature request:  Timer-gate

### ISSUE THREAD

**Issue by tsprivate** [drmibell/node-red-contrib-simple-gate#7]
Hi,

I very often have the used case where I use your Simple-gate node along with the [MyTimeout](https://flows.nodered.org/node/node-red-contrib-mytimeout) node to lock the gate for a certain period of time (e.g. Send Weather update only every 2h, but overwrite when rain is starting)

It would be great to have your gate with an integrated timout-timer to close or open the gate for a certain period of time. As usual controlled via Control topic

Thanks for considering!

below is a code example of my workaround:
![image](https://user-images.githubusercontent.com/41630517/57496579-209b4700-7317-11e9-8b73-e00a68453896.png)

`[{"id":"f5bb6512.75a3a8","type":"inject","z":"4dad7ace.9006c4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":1580,"y":320,"wires":[["ecf8862a.d220d"]]},{"id":"ecf8862a.d220d","type":"gate","z":"4dad7ace.9006c4","name":"","controlTopic":"control","defaultState":"open","openCmd":"open","closeCmd":"close","toggleCmd":"toggle","defaultCmd":"default","persist":false,"x":1790,"y":350,"wires":[["6509d78f.7db23","95a023d3.392128"]]},{"id":"6509d78f.7db23","type":"mytimeout","z":"4dad7ace.9006c4","name":"1h","outtopic":"control","outsafe":"close","outwarning":"","outunsafe":"open","warning":"5","timer":"3600","debug":false,"ndebug":false,"ignoreCase":false,"repeat":false,"again":false,"x":1780,"y":430,"wires":[["8a26057f.cb568"],[]]},{"id":"8a26057f.cb568","type":"change","z":"4dad7ace.9006c4","name":"ctrl","rules":[{"t":"set","p":"topic","pt":"msg","to":"control","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1900,"y":430,"wires":[["ecf8862a.d220d"]]}]`

**Comment by colinl** [comment]
Could you not do that simpler just with a Trigger node?  Send Open immediately then send Close after interval.

**Comment by drmibell** [comment]
I don't see a problem with your "workaround," especially if you consider @colinl 's suggestion, which could work in either of these two flows:
```
[{"id":"f0d7ffb7.5b5988","type":"inject","z":"4fed8f3.ed3687","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":340,"wires":[["68cc6585.d83254","65c736c7.917d"]]},{"id":"68cc6585.d83254","type":"gate","z":"4fed8f3.ed3687","name":"","controlTopic":"control","defaultState":"open","openCmd":"open","closeCmd":"close","toggleCmd":"toggle","defaultCmd":"default","persist":false,"x":310,"y":340,"wires":[["a14e663.706cc18","1a7f8e0c.cf6bb2"]]},{"id":"65c736c7.917d","type":"debug","z":"4fed8f3.ed3687","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":330,"y":300,"wires":[]},{"id":"80ee40ef.be915","type":"change","z":"4fed8f3.ed3687","name":"ctrl","rules":[{"t":"set","p":"topic","pt":"msg","to":"control","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":390,"y":420,"wires":[["68cc6585.d83254"]]},{"id":"a14e663.706cc18","type":"debug","z":"4fed8f3.ed3687","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":490,"y":340,"wires":[]},{"id":"1a7f8e0c.cf6bb2","type":"trigger","z":"4fed8f3.ed3687","op1":"close","op2":"open","op1type":"str","op2type":"str","duration":"10","extend":false,"units":"s","reset":"","bytopic":"all","name":"","x":250,"y":420,"wires":[["80ee40ef.be915"]]},{"id":"70eb8097.f4d43","type":"trigger","z":"4fed8f3.ed3687","op1":"close","op2":"open","op1type":"str","op2type":"str","duration":"10","extend":false,"units":"s","reset":"","bytopic":"all","name":"","x":269,"y":537,"wires":[["befbc395.f6ea68"]]},{"id":"befbc395.f6ea68","type":"change","z":"4fed8f3.ed3687","name":"ctrl","rules":[{"t":"set","p":"topic","pt":"msg","to":"control","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":409,"y":537,"wires":[["32d8d33d.8403fc"]]},{"id":"2cfb40dd.68f75","type":"inject","z":"4fed8f3.ed3687","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":119,"y":497,"wires":[["632798cc.9a2c08","70eb8097.f4d43","32d8d33d.8403fc"]]},{"id":"32d8d33d.8403fc","type":"gate","z":"4fed8f3.ed3687","name":"","controlTopic":"control","defaultState":"open","openCmd":"open","closeCmd":"close","toggleCmd":"toggle","defaultCmd":"default","persist":false,"x":549,"y":497,"wires":[["fe4be83e.c3f7"]]},{"id":"632798cc.9a2c08","type":"debug","z":"4fed8f3.ed3687","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":569,"y":457,"wires":[]},{"id":"fe4be83e.c3f7","type":"debug","z":"4fed8f3.ed3687","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":689,"y":497,"wires":[]}]
```
(with the delay reduced to 10s for testing). Adding a timeout capability to the `gate` node might make sense if there were many other uses for it, but I have not been able to think of any besides your case: pass a message, then close for some interval. Finally, and most important, I think your requirement can be met very simply with the core `delay` node, configured to rate limit and drop intermediate messages:
```
[{"id":"c5a2fe9f.c51fe8","type":"inject","z":"4fed8f3.ed3687","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":700,"wires":[["7b15d9c0.0e7b08"]]},{"id":"7b15d9c0.0e7b08","type":"delay","z":"4fed8f3.ed3687","name":"","pauseType":"rate","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"10","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"x":300,"y":700,"wires":[["c119d6f7.9a07c"]]},{"id":"c119d6f7.9a07c","type":"debug","z":"4fed8f3.ed3687","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":470,"y":700,"wires":[]}]
```
I'm open to further discussion, of course.

**Comment by tsprivate** [comment]
Thanks for all your feedback. I think you are right there are not that any used-cases and my workaround is not necessarily a huge overhead.

I will keep it that way ;)

Thanks , keep up the good work !
