### ISSUE TITLE
suggestion:customizable msg category

### ISSUE THREAD

**Issue by GravityRZ** [drmibell/node-red-contrib-simple-gate#9]
at the moment we can only use msg.topic.
since this is widely used for other things i can not integrate this gate node because it screws up the topic of the current flows
if we could choose our own category this node could be integrated anywere.
eg msg.control, msg.gate

for now i solved the thing with rules in a function.(but this does not show a realtime state)

**Comment by drmibell** [comment]
> at the moment we can only use msg.topic

I assume you mean that only `msg.topic` can be used to control the open or closed state of the `gate`. That is true, but I do not see it as a problem, since control messages (`msg.topic` = `Control Topic`) do not pass through the gate in any case, and this would be true even if `topic` were replaced by some other message property. Your flow will always have to generate control messages separately from the main stream of messages being controlled.

If I have missed your point, and you can post a flow that would benefit from using a different property for gate control, I will be happy to take a look.

**Comment by GravityRZ** [comment]
ah clear. in my case i use msg.topic to hold the id's of lights which are used to control lights with google. i could replace my complete flow to use something else like msg.id but it still has to pass the gate and i believe you stated that this is not the case.

for now i solved the issue by the use of a flow variable which i use as a variable to block/pass things.

it would be nice if the gate could use a user defined msg but still the complete msg needs to pass the gate and not only the payload

**Comment by drmibell** [comment]
>  i use msg.topic to hold the id's of lights

That's fine. The `gate` node will pass those messages when it is open and block them when it is closed. No problem there and no need to change `topic` to some other property.

> i solved the issue by the use of a flow variable which i use as a variable to block/pass things

Lots of people used this method before I wrote the `gate` node, and some still do. The only issue is that if you need many independent gates, then each needs its own flow variable. You have to do the bookkeeping and remember where the variable is set for each gate.

> the complete msg needs to pass the gate and not only the payload

When the gate is open it passes the complete message object with all its properties entirely unchanged. The only exception is when `msg.topic = Control Topic`. Then it tries to interpret `msg.payload` as a command that it can execute, and it sends no output. I'm not sure how you got the idea that only the payload is passed.

It might help if you could post a simple flow that does not behave the way that you would like and describe what you would like it to do.

**Comment by GravityRZ** [comment]
ok . i thought you mentioned that nothing passed so if everything passes when the gate is open it is ok.

at the moment i changed my complete flow and do not need the gate anymore
